---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  serviceAccountName: pipeline
  triggers:
    - name: gitlab-main-listener
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: body.object_attributes.action == 'open'
    # - name: github-main-listener
    #   interceptors:
    #     - ref:
    #         name: "github"
    #       params:
    #         - name: "eventTypes"
    #           value: ["pull_request"]
    #     - ref:
    #         name: "cel"
    #       params:
    #         - name: "filter"
    #           value: body.pull_request.head.ref.startsWith('devhub/') && body.action == 'opened'
      bindings:
        - ref: egress-binding
      template:
        ref: run-egress-{{ .Values.app.name }}

